version: 2
jobs:
  build:
    working_directory: /apps/nanomine-graph
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run:
          name: Clone whyis
          command: cd /apps && git clone git@github.com:tetherless-world/whyis.git whyis-checkout
      - run:
          name: Install whyis
          command: cd whyis-checkout && WHYIS_BRANCH=master ./install.sh
      - run:
          name: Install application
          command: cd whyis && source venv/bin/activate && cd ../nanomine-graph && pip install -e .
      - run:
          name: Run tests
          command: cd whyis && source venv/bin/activate && python manage.py test
