version: 2
jobs:
  build:
    working_directory: ~/nanomine-graph
    docker:
      - image: ubuntu:xenial
    steps:
      - run:
          name: Install dependencies
          command: apt-get update && apt-get install -y git
      - checkout
      - run:
          name: Clone whyis
          command: git clone https://github.com/tetherless-world/whyis.git ~/whyis-checkout
      - run:
          name: Install whyis
          command: cd ~/whyis-checkout && sudo WHYIS_BRANCH=master ./install.sh
      - run:
          name: Move application into place
          command: sudo mv ~/nanomine-graph /apps && sudo chown -R whyis.whyis /apps/nanomine-graph
      - run:
          name: Install application
          command: cd /apps/whyis && source venv/bin/activate && cd ../nanomine-graph && pip install -e .
      - run:
          name: Run tests
          command: cd whyis && source venv/bin/activate && python manage.py test
