version: 2
jobs:
  build:
    working_directory: /apps/nanomine-graph
    docker:
      - image: tetherlessworld/whyis:latest
    steps:
      - checkout
      - run:
          name: Set permissions
          command: chown -R whyis.whyis /apps/nanomine-graph
      - run:
          name: Install application
          command: pip3 install -e .
      - run:
          name: Start the whyis entrypoint and run tests
          command: /docker-entrypoint.sh bash -c "curl -vvv http://localhost:8080/blazegraph/namespace/knowledge/sparql && cd /apps/whyis && python3 manage.py test --ci"
      - store_artifacts:
          path: /apps/whyis/test-results/py/htmlcov
      - store_test_results:
          path: /apps/whyis/test-results
